version: "3.8"

services:
    app:
        build:
            context: .
        env_file:
            - .env
        container_name: fastapi_app
        command: "sh -c 'alembic upgrade head && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000'"
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
    db:
        image: postgres:15.3
        ports:
            - "5432:5432"
        env_file:
            - .env

    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    celery_worker:
        build: .
        command: celery -A tasks.send_email_task:celery worker --loglevel=INFO
        env_file:
            - .env
        depends_on:
            - redis
            - db

    flower:
        build: .
        command: celery -A tasks.send_email_task:celery flower
        ports:
            - "5555:5555"
        env_file:
            - .env
        depends_on:
            - redis
