"""added a category model

Revision ID: 104aa3039604
Revises: 2cdc4c55c746
Create Date: 2023-11-17 23:39:35.067819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString, GUID

# revision identifiers, used by Alembic.
revision: str = '104aa3039604'
down_revision: Union[str, None] = '2cdc4c55c746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
                    sa.Column('title', AutoString(length=200), nullable=False),
                    sa.Column('description', AutoString(), nullable=False),
                    sa.Column('id', GUID(), nullable=False),
                    sa.Column('user_id', GUID(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('note', sa.Column('category_id', GUID(), nullable=True))
    op.create_foreign_key('fk_note_category_id', 'note',
                          'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_note_category_id', 'note', type_='foreignkey')
    op.drop_column('note', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
