"""Added a foreign key

Revision ID: 2cdc4c55c746
Revises: a23fe2b77cb0
Create Date: 2023-11-15 22:32:59.329036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdc4c55c746'
down_revision: Union[str, None] = 'a23fe2b77cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_note_user_id', 'note',
                          'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_note_user_id', 'note', type_='foreignkey')
    # ### end Alembic commands ###
